[workspace]

resolver = "2"

members = [
  "lib_rust_to_gil",
  "gillian",
  "rust_to_gil",
  "gilogic_proc",
  "gilogic",
  "creusillian",
  "tests", 
]

exclude = [
  "test_crates/vec", 
  "test_crates/sort" 
] 
