[workspace]

resolver = "2"

members = [
  "lib_rust_to_gil",
  "gillian",
  "rust_to_gil",
  "gilogic_proc",
  "gilogic",
  "creusillian",
  "tests",
  "cargo-gillian",
]

exclude = ["test_crates/vec", "test_crates/sort", "test_crates/tutorial"]
