[package]
name = "gilogic_proc_dummy"
version = "0.1.0"
edition = "2021"
authors = ["Sacha-Élie Ayoun <sachaayoun@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro=true

[dependencies]
