(lang dune 2.9)

(using dune_site 0.1)

(name gillian-rust)

(authors "Anonymous")

(maintainers "Anonymous")

(generate_opam_files)

(license BSD-3-Clause)

(package
 (name gillian-rust)
 (synopsis "Gillian instantiation for Rust")
 (depends gillian dune-site)
 (sites
  (share runtime)))
