[package]
name = "gillian"
version = "0.1.0"
edition = "2021"
authors = ["Anonymous"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4"
num-traits = "0.2.17"
serde_json = "1.0"
indexmap = "*"
pretty = "0.12.3"
