[package]
name = "gillian"
version = "0.1.0"
edition = "2021"
authors = ["Sacha-Élie Ayoun <sachaayoun@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4"
serde_json = "1.0"