name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Basic setups
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      
      # Rust setup and build/test
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-06-21
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: build
      - uses: actions-rs/cargo@v1
        name: Cargo check
        with:
          command: check
      - uses: actions-rs/cargo@v1
        name: Cargo clippy
        with:
          command: clippy
      
      # OCaml setup and build/test
      - name: Installing esy
        run: sudo npm install -g esy@0.6.12 --unsafe-perm
      - name: Restore Cache
        id: restore-cache
        uses: actions/cache@v1
        with:
          path: Gillian-Rust/_export
          key: ${{ runner.os }}-esy-0.6.12-${{ hashFiles('Gillian-Rust/esy.lock/index.json') }}
          restore-keys: |
            ${{ runner.os }}-esy-0.6.12-
      - name: Esy install
        run: "esy install"
        working-directory: "Gillian-Rust"
      - name: Import Cache
        run: |
          esy import-dependencies _export
          rm -rf _export
        working-directory: "Gillian-Rust"
      - name: Build
        run: "esy"
      - name: Setting dependency cache
        run: |
          esy cleanup .
          esy export-dependencies
        if: steps.restore-cache.outputs.cache-hit != 'true'
        working-directory: "Gillian-Rust"
      - name: build-and-test
        run: "esy test"
        working-directory: "Gillian-Rust"

      # External tests
      - run: ./test_all.sh
