name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      # Basic setups
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      
      - run: cargo build
      - run: cargo check
      - run: cargo clippy

  gil:
    runs-on: ubuntu-latest
    steps:
      # Basic setups
      - uses: actions/checkout@v4
      # OCaml setup and build/test
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "ocaml-variants.5.2.0+options"
      - name: OCaml cache
        id: ocaml-cache
        uses: actions/cache@v3
        env:
          cache-name: cache-ocaml
        with:
          path: _opam
          key: ${{ runner.os }}-${{ env.cache-name }}-ocaml5.2-${{ hashFiles('**/*.opam') }}-${{ hashFiles('**/*.opam.locked') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-ocaml5.2-${{ hashFiles('**/*.opam') }}-
            ${{ runner.os }}-${{ env.cache-name }}-ocaml5.2
      - run: opam install . --deps-only --with-test --locked
        working-directory: "Gillian-Rust"
      - run: opam exec -- dune build @all
        working-directory: "Gillian-Rust"
      - run: opam exec -- dune test
        working-directory: "Gillian-Rust"

      # Run Gillian-Rust on the generated code
      - run: ./test_ci_gil.sh
      
      # Cleanup _opam before updating cache
      - if: ${{ steps.cache-ocaml.outputs.cache-hit != 'true' }}
        name: Cleanup _opam before updating cache
        continue-on-error: true
        run: |
          opam clean
          ls
        working-directory: "Gillian-Rust"
