name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      # Basic setups
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      
      - run: cargo build
      - run: cargo check
      - run: cargo clippy
      - run: cargo test --test ui -- --check

  gil:
    runs-on: ubuntu-latest
    steps:
      # Basic setups
      - uses: actions/checkout@v4
      # OCaml setup and build/test
      - name: Setup Z3
        uses: cda-tum/setup-z3@v1
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "ocaml-variants.5.2.0+options"
      - name: OCaml cache
        id: ocaml-cache
        uses: actions/cache@v3
        env:
          cache-name: cache-ocaml
          dune-cache: true
        with:
          path: _opam
          key: ${{ runner.os }}-${{ env.cache-name }}-ocaml5.2-${{ hashFiles('**/*.opam') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-ocaml5.2
      - run: opam install . --deps-only --with-test
        working-directory: "Gillian-Rust"
      - run: opam exec -- dune build @all
        working-directory: "Gillian-Rust"
      - run: opam exec -- dune test
        working-directory: "Gillian-Rust"

      # Run Gillian-Rust on the generated code
      - run: ./test_ci_gil.sh
      
      # Cleanup _opam before updating cache
      - if: ${{ steps.cache-ocaml.outputs.cache-hit != 'true' }}
        name: Cleanup _opam before updating cache
        continue-on-error: true
        run: |
          opam clean
          ls
        working-directory: "Gillian-Rust"
